### ISSUE TITLE
Highlighted letters in code completion list are really hard to read

### ISSUE THREAD

**Issue by frozenbubble** [artvandelay440/VSCodePopTheme#1]
The highlighted blue letters are hard to read on green background. See attached image.

![image](https://user-images.githubusercontent.com/3799768/33326230-ad5b1d54-d454-11e7-82b5-78a55bf265cb.png)

This is particularly annoying when you are trying to pick one from a longer list and you can't see which one you are on.

**Comment by ArtisanByteCrafter** [comment]
Thanks! I'll have a look at this.

**Comment by ArtisanByteCrafter** [comment]
I believe I have this sorted now, should be released both here and on the marketplace within 24 hours. Thanks!

**Comment by frozenbubble** [comment]
Much appreciated
