### ISSUE TITLE
Highlighted file in explorer is difficult to read

### ISSUE THREAD

**Issue by dwarburt** [artvandelay440/VSCodePopTheme#13]
Platform: Pop!_OS 20.10
```
$ code --version
1.54.2
fd6f3bce6709b121a895d042d343d71f317d74e7
x64
```
![image](https://user-images.githubusercontent.com/52614/111493151-abb7a600-8713-11eb-94a9-3de475bcc3c8.png)

**Comment by ArtisanByteCrafter** [comment]
Hmm, I'm not yet able to reproduce this, what version of the VSCode extension are you using? This is using version 1.0.4

![image](https://user-images.githubusercontent.com/2523522/112060019-a2bb4000-8b2a-11eb-8ca9-c385dfd27435.png)

**Comment by dwarburt** [comment]
hmm, yes I am also on 1.0.4. I'm not sure why my text is blue and yours is white. I renamed my `.vscode` folder and reinstalled this theme with nothing else, and I'm seeing the same results, so I don't think it's another theme or one of my configuration settings. I am on version `1.54.3-1615806378` of code from the microsoft repo.

**Comment by ArtisanByteCrafter** [comment]
No problem, I'll keep investigating and get to the bottom of this.

**Comment by dwarburt** [comment]
This **was** a config setting on my system. I didn't realize that some vscode settings were under `$HOME/.config/Code`. Looks great now, thanks!
