### ISSUE TITLE
Add a License?

### ISSUE THREAD

**Issue by iamjameswalters** [artvandelay440/VSCodePopTheme#14]
I recently switched to [VSCodium](https://vscodium.com/) and didn't see this in [Open-VSX](https://open-vsx.org/). I'd love to use it in VSCodium, but not certain about license terms. Could a license be added to clarify? 

Alternatively, could @ArtisanByteCrafter or someone else with the project with permission to distribute it put it up on Open-VSX? If no one's interested, I might be interested in maintaining it myself (provided I had license clearance).

**Comment by ArtisanByteCrafter** [comment]
@iamjameswalters thanks for the suggestion. I have added a MIT license, so please feel free to use/fork however you need for the extension store you want.

**Comment by iamjameswalters** [comment]
Excellent, thank you! This is my favorite VS Code theme, thanks for your excellent work on this.
