### ISSUE TITLE
Text in buttons do not have good contrast in Light Theme

### ISSUE THREAD

**Issue by initdav** [artvandelay440/VSCodePopTheme#7]
Hello! I'm having the following problem when using the light theme. The text inside the buttons do not have a good contrast, as you can see, the color of the text which is white is not visible when the color of the buttons is a light gray.

![image](https://user-images.githubusercontent.com/2999604/69487948-37c40100-0e31-11ea-959c-3d88929fdad9.png)

It's also happening for the checkboxes, the color of the thick is white, which is not visible when the checkbox background is a light gray.

![image](https://user-images.githubusercontent.com/2999604/69487965-722d9e00-0e31-11ea-91b1-3f4da8cbb0c8.png)

Thanks!

---

**Update:** I managed to get a better contrast in buttons by adding the following configuration in the _settings.json_ file:

```
"workbench.colorCustomizations": {
    "button.foreground": "#5e5e5e"
}
``` 

But I'm not able to get a good contrast in the checkbox, anyway it seems that the error in the checkbox is caused by the Atlassian plugin as it is a webview, not sure if it uses the "native" VSCode checkboxes.

**Comment by ArtisanByteCrafter** [comment]
Thanks! I'll have a look in a few days, when I get the chance.

**Comment by ArtisanByteCrafter** [comment]
I have implemented the button foreground into the theme for the light and color variants. I will be able to update in a few days when i get back from vacation, thanks!

**Comment by initdav** [comment]
Thanks to you!

**Comment by ArtisanByteCrafter** [comment]
I have published an update that should resolve this.
