### ISSUE TITLE
Debug colors

### ISSUE THREAD

**Issue by diegonogueira** [artvandelay440/VSCodePopTheme#8]
The status bar and debug control on Debug mode is not ok...

![status bar](https://user-images.githubusercontent.com/68256/75507179-1853eb80-59bf-11ea-93c3-b1fa8d4f2210.png)

![control](https://user-images.githubusercontent.com/68256/75507205-2dc91580-59bf-11ea-939d-772544662786.png)

**Comment by ArtisanByteCrafter** [comment]
Version 1.0.4 has been published to the VSCode Marketplace to resolve these issues. Thanks again!

![image](https://user-images.githubusercontent.com/2523522/95786616-9094c600-0c9d-11eb-8869-c2ae665ecf94.png)
